#! /bin/bash
set -e

source ~/miscellaneous/error.sh
source ~/miscellaneous/github_repo.sh

pr="$1"
[ -n "$pr" ] || error "PR number required"
dependency="$2"
[ -n "$dependency" ] || error "Dependent PR number required"

tmpdir="$(mktemp -d)"
trap "rm -r $tmpdir" EXIT

git fetch --quiet
read repo_owner repo_name <<<$(github_repo)

read pr_head pr_ref pr_merged <<<$(hub api graphql --raw-field query="query { repository(owner:\"$repo_owner\", name:\"$repo_name\") { issueOrPullRequest(number:$pr) { ... on PullRequest { headRef { name target { oid } } merged } } } }" | jq '.data.repository.issueOrPullRequest' | jq '.headRef.target.oid // empty, .headRef.name // empty, .merged' --raw-output)
[ -n "$pr_head" ] || error "No PR head"
[ -n "$pr_ref" ] || error "No PR ref"

[ "false" == "$pr_merged" ] || error "PR already merged"

git worktree add --detach "$tmpdir" "$pr_head"
cd "$tmpdir"

read dependency_head dependency_merge_commit dependency_merged <<<$(hub api graphql --raw-field query="query { repository(owner:\"$repo_owner\", name:\"$repo_name\") { issueOrPullRequest(number:$dependency) { ... on PullRequest { headRef { target { oid } } mergeCommit { oid } merged } } } }" | jq '.data.repository.issueOrPullRequest' | jq '.headRef.target.oid // empty, .mergeCommit.oid // empty, .merged' --raw-output)
[ -n "$dependency_head" ] || error "No dependency head"
[ -n "$dependency_merge_commit" ] || error "No dependency merge commit"

git merge "$dependency_head" --no-edit --quiet || error "Can not merge dependency into PR"
if [ "true" == "$dependency_merged" ] && [ "$dependency_merge_commit" != "$(git merge-base HEAD $dependency_merge_commit)" ]; then
    git checkout "$dependency_head"
    git merge "$dependency_merge_commit" --no-edit --quiet
    dependency_extra_merge=$(git rev-parse --verify HEAD)
    git checkout "$pr_head" --quiet
    git merge "$dependency_extra_merge" --no-edit --quiet || error "Can not merge dependency into PR"
    git checkout $(git commit-tree $(git write-tree) -p "$pr_head" -p "$dependency_merge_commit" -p "$dependency_head" -m "Merge #$dependency") --quiet
fi
gitk
read # Ctrl+C to abort
git push origin "HEAD:refs/heads/$pr_ref"
