#! /bin/bash
source $(dirname "$BASH_SOURCE")/color.sh
asterisk() {
  if [[ "$2" != "0" ]]; then
    if [[ "$2" != "1" ]]; then
      color "38;5;${1}m" "$2"
    fi
    color "1;38;5;${1}m" '*'
  fi
}
if $(git status >/dev/null 2>/dev/null); then
  referencebranch="origin/master"
  root="$(git rev-parse --show-toplevel)"
  repo="${root##*/}"
  path="${PWD:${#root}}"
  path=${path/#\//>}
  commit=$(git rev-parse HEAD | tr -d "\n")
  mergebase=$(git merge-base $referencebranch $commit | tr -d "\n") 
  mergecount=$(git rev-list ${mergebase}..${commit} --count | tr -d "\n")
  echo -ne "["
  color "32m" "$repo"
  echo -ne ":"
  color "36m" "$referencebranch+$mergecount"
  branches=$(git show-ref | grep --color=never "^$commit" | sed "s#^[^ ]* ##" | grep -v --color=never "^refs/remotes/[^/]*/HEAD$" | sed "s#^refs/remotes/##" | sed "s#^refs/heads/##" | sed "s#^refs/tags/#tags/#" | grep -v "^${referencebranch}$" | sed "s/^/ /" | paste -sd ","  - | sed "s/^ //")
  if [ -n "$branches" ]; then
    echo -ne " "
    color "36m" "($branches)"
  fi
  echo -ne "]"
  echo -ne "$path"
  asterisk "21" $(git branch -l | sed 's/^..//' | grep -v '^(' | wc -l)
  asterisk "226" $(git stash list | wc -l | tr -d " \n")
  asterisk "202" $(git status --porcelain | grep '^[A-Z].' | wc -l)
  asterisk "196" $(git status --porcelain | grep '^.[A-Z]' | wc -l)
  asterisk "201" $(git status --porcelain | grep '^??' | wc -l)
else
  echo -ne "$PWD";
fi
echo -ne '$ '
