#! /usr/local/bin/python3

import argparse
import math
import random
import signal
import subprocess
import sys
import threading
import time

VOICE = random.choice(['Daniel', 'Fiona', 'Karen', 'Samantha', 'Tessa'])

DURATION = 10

def say(message):
    spawn_subprocess('say', '-v', VOICE, '[[volm 0.5]]', message)

def spawn_subprocess(*args):
    def target():
        subprocess.run(args)
    threading.Thread(target=target).start()

def reminder(end):
    remaining = max(math.ceil(end - time.time()), 0)
    hours = int(remaining / 3600)
    minutes = int(remaining % 3600 / 60)
    seconds = int(remaining % 60)
    reminder = ''
    if hours:
        reminder += '{0} hours '.format(hours)
    if minutes:
        reminder += '{0} minutes '.format(minutes)
    if seconds:
        reminder += '{0} seconds '.format(seconds)
    if reminder:
        return reminder + 'remaining'
    else:
        return 'Your time is up'

class PauseException(Exception):
        pass

class StopException(Exception):
        pass

def signal_handler(signum, frame):
    raise PauseException()

def signal_handler2(signum, frame):
    raise StopException()

if __name__ == '__main__':
    try:
        signal.signal(signal.SIGTSTP, signal_handler)
        signal.signal(signal.SIGINT, signal_handler2)
        parser = argparse.ArgumentParser(description='Count down the time.')
        parser.add_argument('duration', type=int)
        args = parser.parse_args()
        start = time.time()
        end = start + args.duration * 60
        paused = None
        said_finished = False
        while True:
            try:
                now = time.time()
                if paused is None:
                    if now < end:
                        left = end - now
                        hours = int(math.ceil(left) / 3600)
                        minutes = int(math.ceil(left) % 3600 / 60)
                        seconds = int(math.ceil(left) % 60)
                        if hours > 0:
                            print(hours, end=':')
                        if hours > 0:
                            print('{0:02d}'.format(minutes), end=':')
                        elif minutes > 0:
                            print(minutes, end=':')
                        print('{0:02d}'.format(seconds))
                        say(reminder(end))
                        time.sleep(left)
                    else:
                        if not said_finished:
                            said_finished = True
                            say('Your time is up!')
                        while True:
                            spawn_subprocess('osascript', '-e', 'beep')
                            time.sleep(1.5)
                else:
                    print('Paused')
                    while True:
                        time.sleep(3600)
            except PauseException:
                if paused is None:
                    paused = time.time()
                else:
                    end = time.time() + (end - paused)
                    paused = None
    except StopException:
        pass
