#! /usr/bin/env bash
set -Eeuo pipefail
trap 'echo error$ ' ERR

color() {
  # $1 is the color
  # $2 is the text
  # $3 is the escape sequence start (optoinal)
  # $4 is the escape sequence end (optional)
  #
  # for color values, see https://robotmoon.com/256-colors/
  echo -ne "$3\x1b[$1$4"
  echo -ne "$2"
  echo -ne "$3\x1b[0m$4"
}

ESCAPE_SEQUENCE_START="$1"
ESCAPE_SEQUENCE_END="$2"

prompt_color() {
  color "$1" "$2" "$ESCAPE_SEQUENCE_START" "$ESCAPE_SEQUENCE_END"
}
print_stat() {
  if [[ "$3" != "0" ]]; then
    prompt_color "1;38;5;${2}m" "$1"
    if [[ "$3" != "1" ]]; then
      prompt_color "38;5;${2}m" "$3"
    fi
  fi
}
if workspace_root="$(jj workspace root 2>/dev/null)"; then
  repo="$(basename "$(jj git remote list | head -n 1)" .git)"
  path="${PWD/#${workspace_root}}"
  path=${path/#\//>}

  prompt_color "32m" "$repo"
  print_stat "*" "21" "$(jj log --no-graph --template '"."' --revisions '@..mutable() ~ description(exact:"")' | wc -c)" # named mutable commits outside working branch
  print_stat "*" "55" "$(jj log --no-graph --template '"."' --revisions '@..mutable() & description(exact:"")' | wc -c)" # unnamed mutable commits outside working branch
  echo -ne ">"
  print_stat "*" "142" "$(jj log --no-graph --template '"."' --revisions '::@- & mutable()' | wc -c)" # mutable commits in working branch
  print_stat "*" "196" "$(jj log --no-graph --template 'self.diff().files().len()' --revisions '@')" # modified files in working copy
  echo -ne "$path"

  # commits from reference to pr base branch
  # commits from pr base branch to pr head
  # How far ahead is reference? PR base?

else
  echo -ne "$PWD";
fi
echo -ne '$ '
